<a href="https://colab.research.google.com/github/anshshori2002/Machine-Learning-Projects/blob/master/CNN_MNIST.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPool2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dropout
from tensorflow.keras.layers import Dense
print("Setup Complete")

Setup Complete


Mnist Dataset is conventionally provided to us as a part of the keras library.

In [ ]:
#Here we are loading the Data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [ ]:
#Here we are reshaping the Data
X_train = X_train.reshape((X_train.shape[0]), X_train.shape[1], X_train.shape[2],1)
X_test = X_test.reshape((X_test.shape[0], X_test.shape[1], X_test.shape[2],1))

In [ ]:
#Here we checking the shape after reshaping
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
#Here we are normalising the pixel values
X_train = X_train/255
X_test = X_test/255

In [ ]:
print(X_train)
print(X_test)

[[[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]]


 [[[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  ...

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.]
   [0.]
   [0.]
   ...
   [0.]
   [0.]
   [0.]]

  [[0.

In [ ]:
print(y_train)
print(y_test)

[5 0 4 ... 5 6 8]
[7 2 1 ... 4 5 6]


In [ ]:
model = Sequential()

In the below line, there we specify 32 filters with size of $3*3$. We are using Rectified linear unit activation function in our layer.Moreover, the input layer has size $28*28$ and they are grey scale.

In [ ]:
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(28,28,1)))

Next we apply the Max Pooling and the Size of Max Pooling is $2*2$ which means it will take the mximum value from $2*2$ matrix of pixels.  

In [ ]:
#Next we apply the max pooling layer
model.add(MaxPool2D(2,2))

In between the Conv2D layes and the dense layer there is a flattened layer.
Flattened servers as a connection between the convolution and the dense layers. Dense is the layer type we will use for our output layer. Dense ia a standard layer type that is used in many cases for neural networks. The flattened method ranges the pixels value from 2D pixels images to 1D array. We are adding a dense layer of 100 neurons in our output layer using the rectified linear unit activation function.

In [ ]:
#Adding Fully Connected Layer as a Side node
model.add(Flatten())
model.add(Dense(100,activation='relu'))

In [ ]:
#Adding output layer
model.add(Dense(10,activation='softmax'))

In [ ]:
#compiling the model
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
#fitting the model
model.fit(X_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 41s 21ms/step - loss: 0.1492 - accuracy: 0.9554
Epoch 2/10
1875/1875 [==============================] - 41s 22ms/step - loss: 0.0508 - accuracy: 0.9844
Epoch 3/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0331 - accuracy: 0.9895
Epoch 4/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0220 - accuracy: 0.9930
Epoch 5/10
1875/1875 [==============================] - 40s 22ms/step - loss: 0.0156 - accuracy: 0.9950
Epoch 6/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0097 - accuracy: 0.9970
Epoch 7/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0081 - accuracy: 0.9972
Epoch 8/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0070 - accuracy: 0.9977
Epoch 9/10
1875/1875 [==============================] - 40s 21ms/step - loss: 0.0057 - accuracy: 0.9981
Epoch 10/10
1875/1875 [==============================] - 40s 21m

In [ ]:
#Evaluating the model
model.evaluate(X_test,y_test)

313/313 [==============================] - 3s 10ms/step - loss: 0.0585 - accuracy: 0.9856


[0.05849554017186165, 0.9855999946594238]